name: angstrom_editor
version: 0.3.0
description: "A package which allows you to embed a level editor into an [Angstrom](https://pub.dev/packages/angstrom) game."
homepage: https://github.com/chrisnorman7/angstrom_editor
environment:
  sdk: ^3.10.2
  flutter: ">=1.17.0"

dependencies:
  angstrom: ^0.2.3
  backstreets_widgets: ^0.39.0
  code_builder: ^4.11.0
  dart_style: ^3.1.3
  flutter:
    sdk: flutter
  flutter_audio_games: ^0.50.3
  flutter_soloud: ^3.4.6
  json_annotation: ^4.9.0
  path: ^1.9.1
  recase: ^4.1.0
  textwrap: ^2.1.0
  uuid: ^4.5.2

dev_dependencies:
  build_runner: ^2.10.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.11.3
scripts:
  watch: dart run build_runner watch -d
  build: dart run build_runner build -d
